### Lists
3.1

In [2]:
# mixed data types OK
# 3.2
MyFirstList = [3, 45, 56, 732]
MyFirstList

[3, 45, 56, 732]

In [3]:
type(MyFirstList)

list

In [4]:
l2 = ["Hello", 24, True, 55.3]

In [5]:
l2

['Hello', 24, True, 55.3]

In [6]:
type(l2)

list

In [7]:
# nested list:
l3 = ["how are you", 55, l2]
l3

['how are you', 55, ['Hello', 24, True, 55.3]]

In [21]:
# iterator/generator for list (same as xrange() in python2):
y = list(range(15))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [22]:
# specify start and end of range:
z = list(range(10,21))
z

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [23]:
# specify the steps to increment by:
w = list(range(100,126,5))
w

[100, 105, 110, 115, 120, 125]

In [30]:
w = ['a', 'b', 'c', 'd', 'e']
w

['a', 'b', 'c', 'd', 'e']

In [32]:
# access list elements [ ]:
w[0]

'a'

In [34]:
# lendgth of list:
len(w)

5

In [37]:
# negative indexation, get last element [-1]:
w[-1]
# in R, that would have "excluded" the firts element...

'e'

In [38]:
w

['a', 'b', 'c', 'd', 'e']

In [41]:
# overwrite values:
w[2] = 66
w

['a', 'b', 66, 'd', 'e']

### Slicing (subsetting a list) [start : finish : step]
3.4

In [45]:
list = ['a','b','c','d','e','f','g','h','i','j']
list

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [46]:
len(list)

10

In [48]:
# extract elements 2 through 7, not including 7 [2:7]
list[2:7]

['c', 'd', 'e', 'f', 'g']

In [55]:
# negative index mix:
list[-8:-3]

['c', 'd', 'e', 'f', 'g']

In [56]:
# only negative index:
list[-8:7]

['c', 'd', 'e', 'f', 'g']

In [58]:
# slice with STEPS and RANGE (from 2, though 9, steps of 2)
list[2:9:2]

['c', 'e', 'g', 'i']

In [59]:
# full list:
list[:]

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [60]:
# start at 2, go all the way:
list[2:]

['c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [71]:
# start at 2, and skip every other
list[2::2]

['c', 'e', 'g', 'i']

In [72]:
# list in REVERSE (step of -1):
list[::-1]

['j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

### Tuples (immutable sequence of values) - ( ) NOT [ ] 
3.5

In [74]:
t1 = (345, 674, 934)
t1

(345, 674, 934)

In [75]:
t1[0]

345

### Functions 
3.6

In [1]:
range(20,31)

range(20, 31)

In [2]:
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [3]:
myList1 = list(range(20,31))

In [4]:
myList1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [5]:
print(myList1)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [6]:
len(myList1)

11

In [7]:
type(myList1)

list

In [8]:
max(myList1)

30

In [9]:
min(myList1)

20

In [10]:
max(11,435,7)

435

## Packages
### 3.7
#### First, open Terminal > conda install scrapy (or pip install scrapy)

In [5]:
# import package
import scrapy

In [15]:
# alternatively, import a specific piece of the package
from scrapy.crawler import CrawlerProcess

## Numpy and Arrays
### 3.8

In [36]:
# list
l = [23245, 27, 546, 215, -1234]
l

[23245, 27, 546, 215, -1234]

In [37]:
# Numpy Arrays (better than core Python Arrays)
import numpy as np

In [38]:
# pass the list l into an array
a = np.array(l)
a

array([23245,    27,   546,   215, -1234])

In [39]:
b = np.array([12, 455, 63.3, True, "a"])

In [40]:
# numpy arrays require same data type
# casted to string in this case..
print(b)

['12' '455' '63.3' 'True' 'a']


In [41]:
# list functions
l.pop()

-1234

In [42]:
# array functions
a.mean()

4559.8000000000002

## Slicing numpy Arrays
### 3.9

In [43]:
a

array([23245,    27,   546,   215, -1234])

In [46]:
# slicing the array does NOT create a copy
a[2:]

array([  546,   215, -1234])

In [47]:
a[2:4]

array([546, 215])

In [49]:
# b here makes another view of array a
b = a[2:4]
b

array([546, 215])

In [51]:
# this adjustment to b, will now update a also
b[:] = 111
a

array([23245,    27,   111,   111, -1234])

In [52]:
# to actually copy an array, use:
c = a.copy()
c

array([23245,    27,   111,   111, -1234])

In [55]:
# now we can safely mess with c, and protect a
c[0] = 0
c

array([    0,    27,   111,   111, -1234])

In [56]:
a

array([23245,    27,   111,   111, -1234])